# render.yaml
services:
  - type: web
    name: noctyx-web
    env: docker
    plan: free # Adjust based on your preferred plan
    region: oregon # Change region if necessary
    image: rbquerubin/noctyx:latest
    envVars:
      - key: MYSQL_HOST
        value: noctyx-mysql
      - key: MYSQL_DATABASE
        value: noctyx
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: comfac123
    disk:
      sizeGB: 1 # Adjust storage size if needed
    healthCheckPath: "/"
    autoDeploy: true

  - type: web
    name: noctyx-phpmyadmin
    env: docker
    plan: free
    region: oregon
    image: rbquerubin/noctyx-php:latest
    envVars:
      - key: PMA_HOST
        value: noctyx-mysql
      - key: PMA_USER
        value: root
      - key: PMA_PASSWORD
        value: comfac123
    disk:
      sizeGB: 1 # Adjust storage size if needed
    healthCheckPath: "/"
    autoDeploy: true

  - type: web
    name: noctyx-mysql
    env: docker
    plan: free
    region: oregon
    image: rbquerubin/noctyx-mysql:latest
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: comfac123
      - key: MYSQL_DATABASE
        value: noctyx
    disk:
      sizeGB: 1 # Adjust storage size if needed
    healthCheckPath: "/"
    autoDeploy: true
