services:
  - name: noctyx-web
    type: web
    env: docker
    image: rbquerubin/noctyx:v3  # Correct the image field
    autoDeploy: true
    envVars:
      - key: PMA_HOST
        value: db
      - key: MYSQL_ROOT_PASSWORD
        value: comfac123
    ports:
      - 80  # Use only the port number without 'port:' prefix

  - name: noctyx-db
    type: web  # 'web' type for database container as well
    env: docker
    image: rbquerubin/noctyx-mysql:v3  # Correct the image field
    autoDeploy: true
    envVars:
      - key: MYSQL_DATABASE
        value: noctyx
      - key: MYSQL_ROOT_PASSWORD
        value: comfac123
    disk:
      sizeGB: 10  # Allocate disk space for MySQL data
    startCommand: ""  # Optional: Leave blank if service starts automatically

  - name: noctyx-phpmyadmin
    type: web
    env: docker
    image: rbquerubin/noctyx-php:v3  # Correct the image field
    autoDeploy: true
    envVars:
      - key: PMA_HOST
        value: db
      - key: MYSQL_ROOT_PASSWORD
        value: comfac123
    ports:
      - 8080  # Use only the port number
