services:
  - type: web
    name: noctyx-web
    env: docker
    plan: free
    region: oregon
    image:
      url: docker.io/rbquerubin/noctyx:v3
    envVars:
      - key: MYSQL_HOST
        value: noctyx-mysql
      - key: MYSQL_DATABASE
        value: noctyx
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: comfac123
    healthCheckPath: "/"
    autoDeploy: true

  - type: web
    name: noctyx-phpmyadmin
    env: docker
    plan: free
    region: oregon
    image:
      url: docker.io/rbquerubin/noctyx-php:v3
    envVars:
      - key: PMA_HOST
        value: noctyx-mysql
      - key: PMA_USER
        value: root
      - key: PMA_PASSWORD
        value: comfac123
    healthCheckPath: "/"
    autoDeploy: true

  - type: web
    name: noctyx-mysql
    env: docker
    plan: free
    region: oregon
    image:
      url: docker.io/rbquerubin/noctyx-mysql:v3
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: comfac123
      - key: MYSQL_DATABASE
        value: noctyx
    healthCheckPath: "/"
    autoDeploy: true
